### PR TITLE
Remove fonts by George Douros

### PR DESCRIPTION
**Pull request by ndr-qef**
The original files have been taken down, but may be available again at a later date (see http://users.teilar.gr/~g1951d/).

### CODE REVIEW

**Comment by ytx21cn** [comment]
The author has closed his website today.

**Comment by Alhadis** [comment]
As a lover of languages, alphabets and history, this discovery hit me pretty hard. :cry: I've e-mailed Douros asking him if he'd be okay with me (or somebody else) hosting the files on GitHub to make them available again...

**Comment by rensbaardman** [comment]
Update: the page is [up again,](http://users.teilar.gr/%7Eg1951d/) although it looks like the zip-packages are a little different than before. Also, Luc Devroye is [hosting them on his page.](http://luc.devroye.org/douros/) See the [page that explains it.](http://luc.devroye.org/fonts-47197.html)

I don't have the time now to re-add them (might have later), should I open an issue for this?

**Comment by commitay** [comment]
> should I open an issue for this?

No, if anyone wants them they should submit a PR.

**Pull request merged**
