### PR TITLE
Update font-hack-nerd-font to 2.0.0

### PR DESCRIPTION
**Pull request by Thammachart**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by neverfox** [comment]
Upgrade is returning a 404 for the zip file.

**Comment by Thammachart** [comment]
I don't know why, the upstream has removed all the v2.0.0 fonts and revert the tag back to 'pre-release'. The link was working perfectly before that.

**Comment by Thammachart** [comment]
Now I know: [Issue from upstream](https://github.com/ryanoasis/nerd-fonts/issues/246#issuecomment-374415430) (The Hack/Knack have 0-byte files, Weather and Octicons Conflict)

**Comment by ryanoasis** [comment]
Working on rebuild this week. conflicts and 0 byte files will be fixed. Sorry and thanks!

**Pull request merged**
