### PR TITLE
Add font Office Code Pro

### PR DESCRIPTION
**Pull request by somebox**
Add font-office-code-pro, a variation of source-code-pro modified for text editors and coding.

https://github.com/nathco/Office-Code-Pro

### CODE REVIEW

**Comment by ndr-qef** [comment]
Thanks. Before merging, we need a small revision: only one of TTF / OTF is needed. Can you remove the `font` stanzas for TTF files?

**Comment by rstacruz** [comment]
:+1:

**Comment by somebox** [comment]
Ok, TTF fonts were removed. I didn't see this covered in the contributing guide, should I add it?

**Comment by ndr-qef** [comment]
Thanks, merged as fc17758.

As for the documentation, if you have time, it would be very welcome! The current docs assume that the contributor is familiar with font technology, which is not very reasonable.

**Pull request closed without merging**
