### PR TITLE
The first version of Apple San Francisco UI Fonts (2016/2/24 release).

### PR DESCRIPTION
**Pull request by byassine52**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not already refused in [closed issues].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-fonts/pulls
[closed issues]: https://github.com/caskroom/homebrew-fonts/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by miccal** [comment]
@vitorgalvao notice that this is a `pkg` install not requiring an `uninstall` and contains:
```
/Library (+)
/Library/Fonts (+)
/Library/Fonts/SFDisplay-Black.otf
/Library/Fonts/SFDisplay-Bold.otf
/Library/Fonts/SFDisplay-Heavy.otf
/Library/Fonts/SFDisplay-Light.otf
/Library/Fonts/SFDisplay-Medium.otf
/Library/Fonts/SFDisplay-Regular.otf
/Library/Fonts/SFDisplay-Semibold.otf
/Library/Fonts/SFDisplay-Thin.otf
/Library/Fonts/SFDisplay-Ultralight.otf
/Library/Fonts/SFText-Bold.otf
/Library/Fonts/SFText-BoldItalic.otf
/Library/Fonts/SFText-Heavy.otf
/Library/Fonts/SFText-HeavyItalic.otf
/Library/Fonts/SFText-Light.otf
/Library/Fonts/SFText-LightItalic.otf
/Library/Fonts/SFText-Medium.otf
/Library/Fonts/SFText-MediumItalic.otf
/Library/Fonts/SFText-Regular.otf
/Library/Fonts/SFText-RegularItalic.otf
/Library/Fonts/SFText-Semibold.otf
/Library/Fonts/SFText-SemiboldItalic.otf
```

**Comment by vitorgalvao** [comment]
I don’t think we want this font in HBC, and I’ll redirect you instead to @joeyhoer’s [repo that has them](https://github.com/joeyhoer/homebrew-extras/tree/master/Casks).

The license for this font is stupidly restrictive. Unbelievably so (emphasis added).

> Subject to the terms of this License, you **may use the Apple Font *solely* for creating mock-ups of user interfaces** to be used in software products running on Apple’s iOS, OS X or tvOS operating systems, as applicable. The foregoing right includes the right to show the Apple Font in screen shots, images, mock-ups or other depictions, digital and/or print, of such software products running solely on iOS, OS X or tvOS.
>
> You may use this Apple Font only for the purposes described in this License **and only if you are a registered Apple Developer**, or as otherwise expressly permitted by Apple in writing.

This is a font you can’t even use at will on your own system. You can’t even change your text editor to use it and Apple makes is incredibly hard to even select it. You have to pay Apple $99/year to use the font, and even then you can only use it to create fake presentations of apps for their systems.

I doubt they’d be happy with us including it in HBC, and frankly this font isn’t requested enough (or at all, there’s a single other issue on it) to justify including it.

Any maintainer should feel free to disagree and continue the discussion, but if they go to such lengths to prevent us from even using the font properly, I question if they’d be happy with this.

**Comment by vitorgalvao** [comment]
On a personal note, I’ll add I think the font looks great and that I think it’s shameful of Apple that they don’t even allow us to use it in our own apps or to view webpages (without workarounds), and that even for the limited uses you need to pay an absurd fee. It shows a weird selfishness that leaves a really bad taste.

**Comment by byassine52** [comment]
Thanks @miccal and @vitorgalvao for the follow-up.
I think we can add a `caveat` as done in @joeyhoer's [repo](https://github.com/joeyhoer/homebrew-extras/tree/master/Casks).
I agree that the license is stupidly strict, but I believe millions of designers and developers working with Apple products and paying the Apple Developer Program fees will like to manage this font and its updates using HBC.
Please rethink about it.

**Comment by miccal** [comment]
@byassine52 for us to even consider it we would need Apple's permission to include it in Cask.

**Comment by vitorgalvao** [comment]
> I think we can add a `caveat` as done in @joeyhoer's [repo]

[`caveats` are for installation-specific instructions](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats).

> I believe millions of designers and developers working with Apple products and paying the Apple Developer Program fees will like to manage this font and its updates using HBC.

Considering there’s no one else asking for this, I highly doubt that. I even doubt a million users know about this repo, let alone millions wanting it here.

**Pull request closed without merging**
