### PR TITLE
Add Wen Quan Yi fonts series

### PR DESCRIPTION
**Pull request by RJHsiao**
Wen Quan Yi (WQY) fonts series are a group of open source CJK fonts
designed for GNU/Linux Desktop Environment.
Website: http://wenq.org/

### CODE REVIEW

**Comment by ndr-qef** [comment]
There is a small mistake we need to correct before merging: to interpolate `version` in `url`, double quotes should be used. Could you amend the commit?

**Comment by RJHsiao** [comment]
Already fixed it.
Sorry for the mistake.

**Comment by ndr-qef** [comment]
Could you squash the commits?

**Comment by RJHsiao** [comment]
Done

**Comment by ndr-qef** [comment]
Thanks.

**Comment by RJHsiao** [comment]
:+1:

**Pull request merged**
