### PR TITLE
Add font-consolas-for-powerline

### LINKED ISSUE #435: Font Request: Consolas for Powerline
Source: https://github.com/eugeii/consolas-powerline-vim

### PR DESCRIPTION
**Pull request by parkr**
Fixes #435.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It’s missing [`license`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#license-stanza-details), which is required.

**Comment by jawshooah** [comment]
Also missing `name`, but so is everything else in this repo...

**Comment by vitorgalvao** [comment]
> Also missing `name`, but so is everything else in this repo...

Yeah, also realised that when seeing this was missing `license`. Filling all those names won’t be fun.

**Comment by parkr** [comment]
> It’s missing license, which is required.

Not sure what the license is. I opened an issue: https://github.com/eugeii/consolas-powerline-vim/issues/4

**Comment by parkr** [comment]
@vitorgalvao I added the license.

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 48af55d340103ed860cfcd3bfa76da6265c02486. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by parkr** [comment]
Thank you, @adityadalal924!

**Pull request closed without merging**
