### PR TITLE
Add new Noto Sans font families

### PR DESCRIPTION
**Pull request by 4cm4k1**
This PR is part of a series of PRs add new font families and updating existing ones as part of the Noto Fonts project’s [Phase 3](https://www.google.com/get/noto/updates/). 

This PR adds the following new Noto Sans font families:
- Noto Sans Adlam Unjoined
- Noto Sans Adlam
- Noto Sans Anatolian Hieroglyphs
- Noto Sans Arabic
- Noto Sans Chakma
- Noto Sans Display
- Noto Sans Mono
- Noto Sans Osage
- Noto Sans Symbols2

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-fonts/pulls
[closed issues]: https://github.com/caskroom/homebrew-fonts/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by 4cm4k1** [comment]
@commitay Travis seems like it’s stalled or something?

**Comment by 4cm4k1** [comment]
Thanks for catching my mistake (abfa819aabe3147618e338f44b4c2b3448e548d9), @commitay! 👍

**Comment by commitay** [comment]
Thanks again for your work on these PRs @4cm4k1!

**Comment by 4cm4k1** [comment]
Of course! I’m here to help! And I’m also passionate about the idea of Noto covering as many human languages and scripts as possible! 😄

**Pull request merged**
