### PR TITLE
updated font-lobster to use new location

### PR DESCRIPTION
**Pull request by sbdchd**

### CODE REVIEW

**Comment by adidalal** [comment]
@vitorgalvao googlecode archive vs github/google/fonts preference?

**Comment by vitorgalvao** [comment]
Preference over github, no doubt.

**Comment by vitorgalvao** [comment]
Preference over github, no doubt. Feel free to merge if you agree.

**Comment by adidalal** [comment]
Was asking because this *only* works because it's a single font file. Other google fonts still need to be pulled from googlecode. Either way, I figure we should be consistent

**Comment by vitorgalvao** [comment]
> Other google fonts still need to be pulled from googlecode.

No need. Those are the ones that use svn, (e.g. [`abeezee`](https://github.com/caskroom/homebrew-fonts/blob/f8d649d7c706880e346a263ce996bb47e7cfe284/Casks/font-abeezee.rb)).

**Pull request merged**
