### PR TITLE
Add font-ibm-plex v0.4.1

### PR DESCRIPTION
**Pull request by alanorth**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-fonts/pulls
[closed issues]: https://github.com/caskroom/homebrew-fonts/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
From: https://github.com/IBM/type/issues/70#issue-272942323

> One requirement for inclusion in that particular package manager's repository is that package releases must be tagged

> See the formula cookbook where it states this requirement: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

This requirement is for `homebrew/core` not Cask, we prefer versioned releases but it isn't a deal breaker.

https://github.com/caskroom/homebrew-fonts/blob/cb406b6bd3096ad5c16e4e1c1edcc3badf75a4a5/Casks/font-space-mono.rb#L1-L13

**Comment by alanorth** [comment]
Thanks, @commitay! I only realized that Caskroom didn't require versioned releases after I posted that tip to the IBM type team. Well happy that it all worked out, as it looks like IBM will start tagging their releases. :)

**Comment by nickv2002** [comment]
Is the plan now to wait for a tagged release before merging?

**Comment by alanorth** [comment]
@nickv2002 I'm not sure what @commitay is waiting for actually. Upstream already tagged the current release and this formula uses it. 🙌

**Comment by nickv2002** [comment]
Works great now with `brew update; brew cask install font-ibm-plex`. Thanks all!

**Pull request merged**
