### PR TITLE
Add all Nerd Font variations

### PR DESCRIPTION
**Pull request by ryanoasis**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free. __*no, but previous PR worked fine, see below__
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses. __*no, but previous PR worked fine, see below__
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully. __*no, but previous PR worked fine, see below__
- [ ] `brew cask uninstall {{cask_file}}` worked successfully. __*no, but previous PR worked fine, see below__
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-fonts/pulls
[closed issues]: https://github.com/caskroom/homebrew-fonts/issues?q=is%3Aissue+is%3Aclosed

* *__did not check all the requirements because I cannot test on macOS, however the previous casks created with the same script eventually worked:__
* previous PRs eventually worked: #913 & #928
* origin of the PRs: https://github.com/ryanoasis/nerd-fonts/issues/72
* cask generated with script from [here](https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/generate-casks.sh)

### CODE REVIEW

**Comment by miccal** [comment]
There are several; `appcast checkpoint mismatch` warnings here - can you please check and confirm your `checkpoints`.

**Comment by miccal** [comment]
Also note that there are already three of these fonts available:

https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-firacode-nerd-font-mono.rb

https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-firacode-nerd-font.rb

https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-hack-nerd-font.rb

Please ensure your PR does not interfere with these existing Casks.

**Comment by ryanoasis** [comment]
> There are several appcast checkpoint mismatch warnings here - can you please check and confirm your checkpoints.

It seems this is due to too many requests? Given that it is giving: "unexpected HTTP response code retrieving appcast: 429". 429 is too many requests. That would make sense why the first few fonts have no issues. Should I try to submit fewer fonts per PR? That might take a while to eventually update all of them.

I checked the `checkpoint` via https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md but seems fine as far as I can tell.

> Also note that there are already three of these fonts available:
>
> https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-firacode-nerd-font-mono.rb
>
> https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-firacode-nerd-font.rb
>
> https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-hack-nerd-font.rb
>
> Please ensure your PR does not interfere with these existing Casks.

It does but that's because the version is now out of date in 2 of them and the `font-hack-nerd-font.rb` now has the 'Mono' versions split into a separate cask.

**Comment by miccal** [comment]
> It seems this is due to too many requests? Given that it is giving: "unexpected HTTP response code retrieving appcast: 429". 429 is too many requests. That would make sense why the first few fonts have no issues. Should I try to submit fewer fonts per PR? That might take a while to eventually update all of them.

I have restarted the build, let's see what happens.

> It does but that's because the version is now out of date in 2 of them and the font-hack-nerd-font.rb now has the 'Mono' versions split into a separate cask.

Can you please open a separate PR to delete these then?

**Comment by miccal** [comment]
> I have restarted the build, let's see what happens.

Same thing, but you're probably right that it is caused by too many requests, so no problem.

**Comment by ryanoasis** [comment]
Thanks yeah looks like that is the problem as far as I can see.

There is nothing that needs deleted just updated 😄

**Comment by miccal** [comment]
OK, I will merge this.

Thanks for your contribution.

**Comment by ryanoasis** [comment]
No problem. Thank you

**Pull request merged**
