### PR TITLE
update iosevka to 1.8.4

### PR DESCRIPTION
**Pull request by pvinis**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There was a PR template you need to fill.

**Comment by pvinis** [comment]
yes but i didnt see anything that needed filling for a simple update like that. but if tou want i can fill it when im on my computer again.

On Mon, May 9, 2016 at 18:57, Vítor Galvão <notifications@github.com> wrote:
There was a PR template you need to fill.

**Comment by vitorgalvao** [comment]
The part about changing a cask is always needed. Specially in this case where you are changing the `url`, one of the commands will verify it works correctly.

**Comment by pvinis** [comment]
ah alright. i will fill it later tonight. i used cask-repair and i thought thats enough verification.

On Mon, May 9, 2016 at 19:04, Vítor Galvão <notifications@github.com> wrote:
The part about changing a cask is always needed. Specially in this case where you are changing the url , one of the commands will verify it works correctly.

**Comment by vitorgalvao** [comment]
You’ll need to [`depends_on formula: 'unar'`](https://github.com/caskroom/homebrew-cask/blob/42437e5fcd93b1a3c95376794e6d5eee2b096160/Casks/hashcat.rb#L10), to be able to unpack the `7z`.

Also, please remove the extra empty line before the last `end`.

**Comment by pvinis** [comment]
alright i will. and i will use the zip again then. i changed to 7z for smaller size, but a dependency for a font.. im not excited about that.

On Mon, May 9, 2016 at 19:12, Vítor Galvão <notifications@github.com> wrote:
You’ll need to depends_on formula: 'unar' [https://github.com/caskroom/homebrew-cask/blob/42437e5fcd93b1a3c95376794e6d5eee2b096160/Casks/hashcat.rb#L10] , to be able to unpack the 7z .

Also, please remove the extra empty line before the last end .

**Comment by vitorgalvao** [comment]
> but a dependency for a font.. im not excited about that.

Agreed.

**Comment by pvinis** [comment]
closed in favor of https://github.com/caskroom/homebrew-fonts/pull/572/

**Pull request closed without merging**
