### PR TITLE
Updates (and adds) Noto font families to Phase 3 versions of Noto Fonts project

### PR DESCRIPTION
**Pull request by 4cm4k1**
This PR brings all the Noto fonts up to date with the Noto Fonts Phase 3 release (described below) by correcting URLs and adding additional styles to existing Noto fonts in this repo and adding brand new Noto fonts to this repo.

> On September 20, 2017, the Noto Fonts project released many more new font families and updated existing ones with new and expanded styles, which were finalized on October 25, 2017.
> Source: https://www.google.com/get/noto/updates/

The following are updated font families:
- Noto Color Emoji
- Noto Emoji
- Noto Kufi Arabic
- Noto Mono
- Noto Naskh Arabic
- Noto Nastaliq Urdu
- Noto Sans Armenian **(new styles)**
- Noto Sans Avestan
- Noto Sans Balinese
- Noto Sans Bamum
- Noto Sans Batak
- Noto Sans Bengali **(new styles)**
- Noto Sans Brahmi
- Noto Sans Buginese
- Noto Sans Buhid
- Noto Sans Canadian Aboriginal
- Noto Sans Carian
- Noto Sans Cham **(new styles)**
- Noto Sans Cherokee **(new styles)**
- Noto Sans CJK JP
- Noto Sans CJK KR
- Noto Sans CJK SC
- Noto Sans CJK TC
- Noto Sans CJK
- Noto Sans Coptic
- Noto Sans Cuneiform
- Noto Sans Cypriot
- Noto Sans Deseret
- Noto Sans Devanagari **(new styles)**
- Noto Sans Egyptian Hieroglyphs
- Noto Sans Ethiopic **(new styles)**
- Noto Sans Georgian **(new styles)**
- Noto Sans Glagolitic
- Noto Sans Gothic
- Noto Sans Gujarati
- Noto Sans Gurmukhi
- Noto Sans Hanunoo
- Noto Sans Hebrew **(new styles)**
- Noto Sans Imperial Aramaic
- Noto Sans Inscriptional Pahlavi
- Noto Sans Inscriptional Parthian
- Noto Sans Javanese
- Noto Sans Kaithi
- Noto Sans Kannada
- Noto Sans Kayah Li
- Noto Sans Kharoshthi
- Noto Sans Khmer **(new styles)**
- Noto Sans Lao **(new styles)**
- Noto Sans Lepcha
- Noto Sans Limbu
- Noto Sans Linear B
- Noto Sans Lisu
- Noto Sans Lycian
- Noto Sans Lydian
- Noto Sans Malayalam
- Noto Sans Mandaic
- Noto Sans Meetei Mayek
- Noto Sans Mongolian
- Noto Sans Myanmar **(new styles)**
- Noto Sans NKo
- Noto Sans New Tai Lue
- Noto Sans Ogham
- Noto Sans Ol Chiki
- Noto Sans Old Italic
- Noto Sans Old Persian
- Noto Sans Old South Arabian
- Noto Sans Old Turkic
- Noto Sans Oriya
- Noto Sans Osmanya
- Noto Sans Phags Pa
- Noto Sans Phoenician
- Noto Sans Rejang
- Noto Sans Runic
- Noto Sans Samaritan
- Noto Sans Saurashtra
- Noto Sans Shavian
- Noto Sans Sinhala **(new styles)**
- Noto Sans Sundanese
- Noto Sans Syloti Nagri
- Noto Sans Symbols **(new styles)**
- Noto Sans Syriac Eastern
- Noto Sans Syriac Estrangela
- Noto Sans Syriac Western
- Noto Sans Tagalog
- Noto Sans Tagbanwa
- Noto Sans Tai Le
- Noto Sans Tai Tham
- Noto Sans Tai Viet
- Noto Sans Tamil **(new styles)**
- Noto Sans Telugu
- Noto Sans Thaana
- Noto Sans Thai **(new styles)**
- Noto Sans Tibetan
- Noto Sans Tifinagh
- Noto Sans Ugaritic
- Noto Sans Vai
- Noto Sans Yi
- Noto Sans **(new styles)**
- Noto Serif Armenian **(new styles)**
- Noto Serif CJK JP
- Noto Serif CJK KR
- Noto Serif CJK SC
- Noto Serif CJK TC
- Noto Serif CJK
- Noto Serif Georgian **(new styles)**
- Noto Serif Khmer **(new styles)**
- Noto Serif Lao **(new styles)**
- Noto Serif Thai **(new styles)**
- Noto Serif **(new styles)**

The following are brand new font families:
- Noto Sans Adlam Unjoined
- Noto Sans Adlam
- Noto Sans Anatolian Hieroglyphs
- Noto Sans Arabic
- Noto Sans Chakma
- Noto Sans Display
- Noto Sans Mono
- Noto Sans Osage
- Noto Sans Symbols2
- Noto Serif Bengali
- Noto Serif Display
- Noto Serif Devanagari
- Noto Serif Ethiopic
- Noto Serif Gujarati
- Noto Serif Hebrew
- Noto Serif Kannada
- Noto Serif Malayalam
- Noto Serif Myanmar
- Noto Serif Sinhala
- Noto Serif Tamil
- Noto Serif Telugu

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-fonts/pulls
[closed issues]: https://github.com/caskroom/homebrew-fonts/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
@4cm4k1 I realise this is currently WIP but when it's ready to be merged can you please split it into smaller PRs? A single PR with a very large diff that adds new Casks and makes changes to existing ones it hard to review. Our CI will probably also have issues with this because of the number of Casks.

**Comment by 4cm4k1** [comment]
@commitay Sure! Do we want an individual PR for each new/updated Cask? Or to what degree can I group them?

**Comment by commitay** [comment]
I've increased the CI cap to test 15 at a time, so groups smaller then 15 and separated by new or existing would be good. Thanks!

**Comment by 4cm4k1** [comment]
@commitay Great, I’m going to close this PR, and I’ll have several smaller ones shortly. 😄

**Comment by commitay** [comment]
Thank you!

**Comment by 4cm4k1** [comment]
@commitay Done!

**Comment by commitay** [comment]
Great! They all all look 👍 , we'll let the CI work though them and should be merged soon. Thanks again!

**Pull request closed without merging**
