### PR TITLE
add font-roboto-mono-for-powerline

### PR DESCRIPTION
**Pull request by iandrewt**
#### Adding a new cask

- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-fonts/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-fonts/issues) where that cask was already refused.
- [x] When naming the cask, followed the [reference](https://github.com/caskroom/homebrew-fonts/blob/master/CONTRIBUTING.md#naming-font-casks).
- [x] Commit message includes cask’s name.
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

Audit not passed becasue ` - at lesat one name stanza is required`

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Why haven’t you run the `audit` command?

That one is particularly important in this repo.

**Comment by iandrewt** [comment]
I did run the audit command, but it failed because of a missing name stanza. It seems most of the other Powerline fonts have the same issue.

**Comment by vitorgalvao** [comment]
[We know](https://github.com/caskroom/homebrew-fonts/issues/437).

You need to add a `name` to this one. We can’t merge casks that don’t pass audit.

**Comment by iandrewt** [comment]
I think I need to start this PR from scratch, my local branch seems to have broken from not having the latest updates before starting. I'll close and reopen this PR when I'm done, with the appropriate fixes added.

**Pull request closed without merging**
