### PR TITLE
Add font-cooper-hewitt

### PR DESCRIPTION
**Pull request by leafac**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-fonts/pulls
[closed issues]: https://github.com/caskroom/homebrew-fonts/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by leafac** [comment]
@vitorgalvao Thank you for looking at my pull request and for fixing it to the project’s standards.

Is there anything else you want me to do before this is ready to merge?

**Comment by leafac** [comment]
I’m sorry for the confusion, but I actually found a better source for the font. Please consider `ff7e89e`.

**Comment by vitorgalvao** [comment]
> I squashed the commits to keep the history clean

Thank you, but no need. Github now allows us to squash at the time of merging. In fact, for small changes like this we actively prefer if changes are not squashed, as they make it easier to review just the latest changes.

**Comment by leafac** [comment]
Thank you for merging my contribution and thank you for educating me on this GitHub feature.

**Pull request merged**
