### PR TITLE
Add Indian Type Foundry fonts

### PR DESCRIPTION
**Pull request by guerrero**
Add the following fonts from Indian Type Foundry:
- Halant
- Hind
- Kalam
- Karma
- Khand
- Laila
- Poppins
- Rajdhani
- Rozha One
- Sarpanch
- Teko
- Tillana

### CODE REVIEW

**Comment by vitorgalvao** [comment]
All of them have a “no newline at end of file” warning. Those are [actually meaningful](http://unix.stackexchange.com/a/18789).

**Comment by guerrero** [comment]
Fixed, thanks for spot it @vitorgalvao. I've also added a license `field` for all of these fonts.

As a side note, it would be nice to add a `.gitattributes` file with `* text=auto` to this repo to normalize file line endings. More info [here](http://stackoverflow.com/questions/21472971/what-is-the-purpose-of-text-auto-in-gitattributes)

**Comment by vitorgalvao** [comment]
> As a side note, it would be nice to add a `.gitattributes` file with `* text=auto` to this repo to normalize file line endings. More info [here](http://stackoverflow.com/questions/21472971/what-is-the-purpose-of-text-auto-in-gitattributes)

Looks good, will do.

On another note, all of this could benefit from an appcast. Example:

```ruby
cask :v1 => 'font-halant' do
  version '2.000'
  sha256 'd65e1077b7c3d3ca42cf41f8ee2db4f6da5cc8aa6f615d18a1bb497f8e37ca63'

  url 'https://github.com/itfoundry/halant/releases/download/v2.000/halant-2_000.zip'
  appcast 'https://github.com/itfoundry/halant/releases.atom'
  homepage 'https://github.com/itfoundry/halant'
  license :ofl

  font 'Halant-Bold.otf'
  font 'Halant-Light.otf'
  font 'Halant-Medium.otf'
  font 'Halant-Regular.otf'
  font 'Halant-SemiBold.otf'
end
```

All of them will follow the same pattern.

Finally, could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by guerrero** [comment]
Done. Thanks for the support

**Comment by vitorgalvao** [comment]
Thank you for the contribution.

**Pull request merged**
