### PR TITLE
Add DDC Hardware

### PR DESCRIPTION
**Pull request by danielbayley**
Free for personal use.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-fonts/pulls
[closed issues]: https://github.com/caskroom/homebrew-fonts/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
> Free for personal use.

Not exactly. It's "Pay-What-You-Want". https://losttype.com/font/?name=ddc_hardware

Ping @vitorgalvao

**Comment by vitorgalvao** [comment]
Technically you may want to pay zero and users are expected to know what they are downloading. It’s unlikely you’ll download a font without first knowing what it is. It’s conceivable a user has already paid more than zero and wants an easy way to install via HBC.

All that said, even though that abides by the letter of the law, it probably does not abide by its spirit and they’re expecting users to contribute *something*. Aaron Draplin is a relatively well-known professional designer. I also think we should try to avoid fonts with restrictive licenses, especially if they’re not too well-known.

I can justify both inclusion and refusal. If I had to guess what the owners of that website would want, I’m guessing they’d prefer refusal and I’m fine with that.

**Comment by danielbayley** [comment]
Well in my _homebrew-adobe_ tap for example, in this kind of situation I have included `caveat`s saying something along the lines of `Please consider a voluntary purchase if you like this`… along with the link.

Would that be worth doing as a comprimise?

**Comment by vitorgalvao** [comment]
> Would that be worth doing as a comprimise?

[No](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md):

> To avoid flooding users with too many messages (thus desensitising them to the important ones), `caveats` should be used sparingly and exclusively for installation-related matters.

**Comment by commitay** [comment]
Thanks nonetheless for the PRs!

**Pull request closed without merging**
